/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AwDatepicker {
    'minYear': number;
  }
  interface AwDatepickerAttributes extends StencilHTMLAttributes {
    'minYear'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AwDatepicker': Components.AwDatepicker;
  }

  interface StencilIntrinsicElements {
    'aw-datepicker': Components.AwDatepickerAttributes;
  }


  interface HTMLAwDatepickerElement extends Components.AwDatepicker, HTMLStencilElement {}
  var HTMLAwDatepickerElement: {
    prototype: HTMLAwDatepickerElement;
    new (): HTMLAwDatepickerElement;
  };

  interface HTMLElementTagNameMap {
    'aw-datepicker': HTMLAwDatepickerElement
  }

  interface ElementTagNameMap {
    'aw-datepicker': HTMLAwDatepickerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
